Moved tmux format updating to tmx script.
[Details]
Moved the UpdateTmuxFormat function which was in the bash_global to now
be apart of the tmx script. The functionality can be accessed by using
the -u option to update, or -x option to delete a tmux format. All tmx
functionality is now self-contained inside the tmx script.

[File's changed]
	modified:   .bash_global
	modified:   bin/tmx

diff --git a/bin/tmx b/bin/tmx
--- a/bin/tmx
+++ b/bin/tmx
@@ -4,15 +4,22 @@ command -v tmux >/dev/null 2>&1 || { printf "tmx requires tmux but it is not ins
 Aborting." >&2; exit 1; }
 
 # Proccess cmd line options
-while getopts ":hlf:d:" opt; do
+while getopts ":hluxf:d:" opt; do
   case ${opt} in
     h )
-      echo "Usage: tmx [-h] [-f format] [-d start dir] [name]"
+      echo "Usage: tmx [-hlud] [-f format] [-d start dir] [name]"
       echo "where options include:"
       echo "  -h"
       echo "    Display this message"
       echo "  -l"
       echo "    List active sessions and stored formats"
+      echo "  -u"
+      echo "    Update or create a stored tmx format instead of starting a new one."
+      echo "    Uses the -f, -d options accordingly, <name> is mandatory."
+      echo "  -x"
+      echo "    Delete a tmux format with the supplied name. Note the <name>"
+      echo "    argument is mandatory with this option, and all other options"
+      echo "    are ignored"
       echo "  -f format"
       echo "    Format the new tmux session using the format string given"
       echo "    where <format> = \"{[<op>[<ctrl>]][{<cmd>}]}\""
@@ -26,7 +33,7 @@ while getopts ":hlf:d:" opt; do
       exit 0
       ;;
     l )
-      if tmux info &> /dev/null; then
+      if tmux list-sessions &> /dev/null; then
         active=1
       fi
       echo "Active sessions:"
@@ -44,11 +51,19 @@ while getopts ":hlf:d:" opt; do
       awk -F "::" '{print $1":","(\""$2"\",",$3")"}' ~/bin/.tmux.formats
       exit 0
       ;;
+    u )
+      update=1
+      ;;
+    x )
+      delete=1
+      ;;
     f )
       format=$OPTARG
+      f=1
       ;;
     d )
       dir=$OPTARG
+      d=1
       ;;
     \? )
       echo "Invalid option: $OPTARG" 1>&2
@@ -59,6 +74,37 @@ while getopts ":hlf:d:" opt; do
   esac
 done
 shift $((OPTIND -1))
+
+if [ "$update" == "1" ] || [ "$delete" == "1" ]; then
+  if [ $# = 0 ]; then
+    echo "ERROR: name not given for format modification, exiting..."
+    exit 1
+  fi
+  if [ "$update" == "1" ]; then
+    # add start dir to the end if needed
+    if [ "$dir" != "" ]; then
+      dir="::$(readlink -f "$(echo ${dir/"~"/~})")"
+    fi
+    # Add format and dir to the formats file, or update if it exists
+    if [ "$(grep "^$1" ~/bin/.tmux.formats)" != "" ]; then
+      echo "Updating format for \"$1\""
+      if [ ! "$f" ]; then
+        format="\\1"
+      fi
+      if [ ! "$d" ]; then
+        dir="\\2"
+      fi
+      sed -i -E "s#^$1::([^:]*)(::[^:]+)?#$1::${format}${dir}#" ~/bin/.tmux.formats
+    else
+      echo "Adding format for \"$1\""
+      echo "$1::${format}${dir}" >> ~/bin/.tmux.formats
+    fi
+  elif [ "$delete" == "1" ]; then
+    echo "Deleting format for \"$1\""
+    sed -i "/^$1::.*/d" ~/bin/.tmux.formats
+  fi
+  exit 0
+fi
 
 # name the workspace
 SESSION="Workspace"
