Fixed up tmx command and all bash history.
[Details]
Added improvements to the tmx command so that it respects the bash
history of the shell that opens it, and adds the history of the tmux
session back to that shell on exit. To do this history editing, the
script needed to be sourced which is now done as a function in the
bash_global. Also added options to the bash_global for managing bash
history more naturally in general.

[File's changed]
	modified:   .bash_global
	modified:   bin/tmx

diff --git a/bin/tmx b/bin/tmx
--- a/bin/tmx
+++ b/bin/tmx
@@ -48,6 +48,10 @@ else
 	SESSION=$1
 fi
 
+if [ "$HISTFILE" != "" ]; then
+  history -a
+fi
+
 # if the session is already running, just attach to it.
 tmux has-session -t $SESSION > /dev/null 2>&1
 if [ $? -eq 0 ]; then
@@ -55,88 +59,90 @@ if [ $? -eq 0 ]; then
   sleep 0.1
   sett $SESSION
   tmux -2 attach -t $SESSION
-  exit 0;
-fi
-
-if [ "$format" == "" ]; then
-  IFS=$'\n'
-  if [ ! -f ~/bin/.tmux.formats ]; then
-    touch ~/bin/.tmux.formats
-  fi
-  for line in $(cat ~/bin/.tmux.formats); do
-    name=$(echo "$line" | awk -F "::" '{print $1}')
-    form=$(echo "$line" | awk -F "::" '{print $2}')
-    d=$(echo "$line" | awk -F "::" '{print $3}')
-    #name="${line%%::*}"
-    #form="${line##*::}"
-    if [ "$SESSION" == "$name" ]; then
-      format="$form"
-      dir="$d"
-      echo "Retrived format specified for \"$name\""
-      break
+else
+  if [ "$format" == "" ]; then
+    IFS=$'\n'
+    if [ ! -f ~/bin/.tmux.formats ]; then
+      touch ~/bin/.tmux.formats
     fi
-  done
-  unset IFS
-fi
-dir="$(readlink -f "$(echo ${dir/"~"/~})")"
-if [ "$dir" != "" ] && [ -d "$dir" ] ; then
-  cd "$dir"
-fi
+    for line in $(cat ~/bin/.tmux.formats); do
+      name=$(echo "$line" | awk -F "::" '{print $1}')
+      form=$(echo "$line" | awk -F "::" '{print $2}')
+      d=$(echo "$line" | awk -F "::" '{print $3}')
+      #name="${line%%::*}"
+      #form="${line##*::}"
+      if [ "$SESSION" == "$name" ]; then
+        format="$form"
+        dir="$d"
+        echo "Retrived format specified for \"$name\""
+        break
+      fi
+    done
+    unset IFS
+  fi
+  dir="$(readlink -f "$(echo ${dir/"~"/~})")"
+  if [ "$dir" != "" ] && [ -d "$dir" ] ; then
+    cd "$dir"
+  fi
 
-# create a new session, named $SESSION, and detach from it
-tmux -2 new-session -n $SESSION -d -s $SESSION
+  # create a new session, named $SESSION, and detach from it
+  tmux -2 new-session -n $SESSION -d -s $SESSION
 
-tmux set set-titles on
-tmux set set-titles-string $SESSION
-tmux set-option -g base-index 1
-tmux set-window-option -t $SESSION -g automatic-rename off
-tmux set-window-option -g pane-base-index 1
+  tmux set set-titles on
+  tmux set set-titles-string $SESSION
+  tmux set-option -g base-index 1
+  tmux set-window-option -t $SESSION -g automatic-rename off
+  tmux set-window-option -g pane-base-index 1
 
-# Now populate the session with the windows you use every day
-tmux new-window -t $SESSION:0 -k -n Untitled-window
-if [ ! -z "$format" ]; then
-  i=0
-  size=${#format}
-  while [ $i -lt $size ]; do
-    case ${format:$i:1} in
-      \| )
-        tmux split-window -h -p 50
-        ;;
-      _ )
-        tmux split-window -v -p 50
-        ;;
-      ^ )
-        tmux select-pane -U
-        ;;
-      v )
-        tmux select-pane -D
-        ;;
-      \> )
-        tmux select-pane -R
-        ;;
-      \< )
-        tmux select-pane -L
-        ;;
-      { )
-        s=$(expr $i + 1)
-        i=$(expr $i + 1)
-        while [ "${format:$i:1}" != "}" ]; do
+  # Now populate the session with the windows you use every day
+  if [ ! -z "$format" ]; then
+    i=0
+    size=${#format}
+    while [ $i -lt $size ]; do
+      case ${format:$i:1} in
+        \| )
+          tmux split-window -h -p 50
+          ;;
+        _ )
+          tmux split-window -v -p 50
+          ;;
+        ^ )
+          tmux select-pane -U
+          ;;
+        v )
+          tmux select-pane -D
+          ;;
+        \> )
+          tmux select-pane -R
+          ;;
+        \< )
+          tmux select-pane -L
+          ;;
+        { )
+          s=$(expr $i + 1)
           i=$(expr $i + 1)
-        done
-        len=$(expr $i - $s)
-        com=${format:$s:$len}
-        #echo "command: \"$com\""
-        tmux send-keys "$com" Enter
-        ;;
-      * )
-        echo "Could not parse ${format:$i:1}"
-        ;;
-    esac
-    i=$(expr $i + 1)
-  done
-fi
+          while [ "${format:$i:1}" != "}" ]; do
+            i=$(expr $i + 1)
+          done
+          len=$(expr $i - $s)
+          com=${format:$s:$len}
+          #echo "command: \"$com\""
+          tmux send-keys "$com" Enter
+          ;;
+        * )
+          echo "Could not parse ${format:$i:1}"
+          ;;
+      esac
+      i=$(expr $i + 1)
+    done
+  fi
 
-# all done. select starting window and get to work
-tmux set-window-option -t $SESSION:0 automatic-rename off
-tmux select-window -t $SESSION:0
-tmux -2 attach -t $SESSION
+  # all done. select starting window and get to work
+  tmux -2 attach -t $SESSION
+fi
+# clean up after session close (not detatch)
+tmux has-session -t $SESSION > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+  #echo "Time for clean up..."
+  history -n
+fi
